### ISSUE TITLE
issue with protobuf package

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/ExplainerLibraries#3]
Hi, 

I have an issue when trying to build and execute a Docker image of this repository.

It looks like the protobuf package (used by Tensorflow) needs updated librairies

see the traceback below (when executing the ```app.py``` script):

```
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from resources.explainers.tabular.dicePublic import DicePublic
  File "/app/resources/explainers/tabular/dicePublic.py", line 2, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

**Comment by jesusdarias** [comment]
This seems to be an issue related to the dockerization. I replicated the process of building the Docker image and the workaround was to use a ```3.20.X``` version of ```protobuf```(as the traceback suggests). I already updated the ```requirements.txt``` file. However, I was still not able to fully execute the Docker image since there is a problem with the ```cv2``` library:

```
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    from resources.explainers.images.gradcamTorch import GradCamTorch
  File "/app/resources/explainers/images/gradcamTorch.py", line 9, in <module>
    from pytorch_grad_cam.utils.image import show_cam_on_image,preprocess_image
  File "/usr/local/lib/python3.8/site-packages/pytorch_grad_cam/__init__.py", line 1, in <module>
    from pytorch_grad_cam.grad_cam import GradCAM
  File "/usr/local/lib/python3.8/site-packages/pytorch_grad_cam/grad_cam.py", line 2, in <module>
    from pytorch_grad_cam.base_cam import BaseCAM
  File "/usr/local/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 6, in <module>
    from pytorch_grad_cam.utils.svd_on_activations import get_2d_projection
  File "/usr/local/lib/python3.8/site-packages/pytorch_grad_cam/utils/__init__.py", line 1, in <module>
    from pytorch_grad_cam.utils.image import deprocess_image
  File "/usr/local/lib/python3.8/site-packages/pytorch_grad_cam/utils/image.py", line 1, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
I will refer you to this [thread](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo). It may be necessary to install ```libgl1``` separately in the Dockerfile.

**Comment by bfleisch** [comment]
hi Jesus, 

thanks a lot for this - I've updated the Dockerfile accordingly and created a new image. Let's see if this works...
